/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuizGeneratingRouteImport } from './routes/quiz.generating'
import { Route as QuizQuizIdRouteImport } from './routes/quiz.$quizId'
import { Route as QuizQuizIdIndexRouteImport } from './routes/quiz.$quizId.index'
import { Route as QuizQuizIdResultRouteImport } from './routes/quiz.$quizId.result'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizGeneratingRoute = QuizGeneratingRouteImport.update({
  id: '/generating',
  path: '/generating',
  getParentRoute: () => QuizRoute,
} as any)
const QuizQuizIdRoute = QuizQuizIdRouteImport.update({
  id: '/$quizId',
  path: '/$quizId',
  getParentRoute: () => QuizRoute,
} as any)
const QuizQuizIdIndexRoute = QuizQuizIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => QuizQuizIdRoute,
} as any)
const QuizQuizIdResultRoute = QuizQuizIdResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => QuizQuizIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/quiz': typeof QuizRouteWithChildren
  '/signup': typeof SignupRoute
  '/quiz/$quizId': typeof QuizQuizIdRouteWithChildren
  '/quiz/generating': typeof QuizGeneratingRoute
  '/quiz/$quizId/result': typeof QuizQuizIdResultRoute
  '/quiz/$quizId/': typeof QuizQuizIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/quiz': typeof QuizRouteWithChildren
  '/signup': typeof SignupRoute
  '/quiz/generating': typeof QuizGeneratingRoute
  '/quiz/$quizId/result': typeof QuizQuizIdResultRoute
  '/quiz/$quizId': typeof QuizQuizIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/quiz': typeof QuizRouteWithChildren
  '/signup': typeof SignupRoute
  '/quiz/$quizId': typeof QuizQuizIdRouteWithChildren
  '/quiz/generating': typeof QuizGeneratingRoute
  '/quiz/$quizId/result': typeof QuizQuizIdResultRoute
  '/quiz/$quizId/': typeof QuizQuizIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/quiz'
    | '/signup'
    | '/quiz/$quizId'
    | '/quiz/generating'
    | '/quiz/$quizId/result'
    | '/quiz/$quizId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/quiz'
    | '/signup'
    | '/quiz/generating'
    | '/quiz/$quizId/result'
    | '/quiz/$quizId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/quiz'
    | '/signup'
    | '/quiz/$quizId'
    | '/quiz/generating'
    | '/quiz/$quizId/result'
    | '/quiz/$quizId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  QuizRoute: typeof QuizRouteWithChildren
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/generating': {
      id: '/quiz/generating'
      path: '/generating'
      fullPath: '/quiz/generating'
      preLoaderRoute: typeof QuizGeneratingRouteImport
      parentRoute: typeof QuizRoute
    }
    '/quiz/$quizId': {
      id: '/quiz/$quizId'
      path: '/$quizId'
      fullPath: '/quiz/$quizId'
      preLoaderRoute: typeof QuizQuizIdRouteImport
      parentRoute: typeof QuizRoute
    }
    '/quiz/$quizId/': {
      id: '/quiz/$quizId/'
      path: '/'
      fullPath: '/quiz/$quizId/'
      preLoaderRoute: typeof QuizQuizIdIndexRouteImport
      parentRoute: typeof QuizQuizIdRoute
    }
    '/quiz/$quizId/result': {
      id: '/quiz/$quizId/result'
      path: '/result'
      fullPath: '/quiz/$quizId/result'
      preLoaderRoute: typeof QuizQuizIdResultRouteImport
      parentRoute: typeof QuizQuizIdRoute
    }
  }
}

interface QuizQuizIdRouteChildren {
  QuizQuizIdResultRoute: typeof QuizQuizIdResultRoute
  QuizQuizIdIndexRoute: typeof QuizQuizIdIndexRoute
}

const QuizQuizIdRouteChildren: QuizQuizIdRouteChildren = {
  QuizQuizIdResultRoute: QuizQuizIdResultRoute,
  QuizQuizIdIndexRoute: QuizQuizIdIndexRoute,
}

const QuizQuizIdRouteWithChildren = QuizQuizIdRoute._addFileChildren(
  QuizQuizIdRouteChildren,
)

interface QuizRouteChildren {
  QuizQuizIdRoute: typeof QuizQuizIdRouteWithChildren
  QuizGeneratingRoute: typeof QuizGeneratingRoute
}

const QuizRouteChildren: QuizRouteChildren = {
  QuizQuizIdRoute: QuizQuizIdRouteWithChildren,
  QuizGeneratingRoute: QuizGeneratingRoute,
}

const QuizRouteWithChildren = QuizRoute._addFileChildren(QuizRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  QuizRoute: QuizRouteWithChildren,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
